[package]
name = "staking_contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.2.0"
borsh = "1.5.7"
borsh-derive = "1.5.7"

[dev-dependencies]
litesvm = "0.7.0"
solana-sdk = "3.0.0"
